# Generated by Django 4.0 on 2021-12-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='image',
            new_name='file',
        ),
    ]
